require 'options'
require 'keymaps'
require 'plugins'
require 'colorscheme'
require 'treesitter'
require 'nvimtree'
require 'telescope'
require 'autopairs'
require 'comments'
require 'lualine'
require 'nvimcmp'
require 'nvimlsp'
require 'rusttools'

